name: hi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  mapbox_maps_flutter: ^2.0.0
  geolocator: ^13.0.0
  permission_handler: ^11.3.0
  record: ^6.2.0
  audioplayers: ^6.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.0
  path_provider: ^2.1.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
